// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "APDemo",
    platforms: [
        .iOS("13.0")
    ],
    products: [
        .iOSApplication(
            name: "APDemo",
            targets: ["UIKItExampleModule"],
            bundleIdentifier: "jp.co.lacicu.apdemo",
            teamIdentifier: "L6KA777G24",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "AccelParts", path: "../")
    ],
    targets: [
        .executableTarget(
            name: "UIKItExampleModule",
            dependencies: [
                "Shared",
                "AccelParts"
            ]
        ),
        .target(
            name: "Shared"
        )
    ]
)